// @ts-check
import fs from 'node:fs';
import path from 'node:path';
import { defineConfig } from 'astro/config';
import { unified } from '@astrojs/markdown-remark';
import rehypeExternalLinks from 'rehype-external-links';

// `astro dev` serves live source via Vite — it never reads from dist/, so
// /pagefind/pagefind.js (only generated by the `pagefind` CLI step in
// `npm run build`, into dist/pagefind/) 404s under plain `npm run dev`,
// making /search look broken (silently falls back to only matching
// external Medical Conditions topic names). This serves whatever
// dist/pagefind/ exists from the last build directly during dev, so the
// normal dev workflow doesn't require switching to `astro preview` just to
// test search. Still requires at least one prior `npm run build` — there's
// no way around that; the index has to be generated from *something*.
function serveDistPagefindDuringDev() {
  return {
    name: 'serve-dist-pagefind-during-dev',
    hooks: {
      'astro:server:setup': ({ server }) => {
        server.middlewares.use((req, res, next) => {
          if (!req.url?.startsWith('/pagefind/')) return next();
          // Pagefind's loader appends a cache-busting query string
          // (e.g. ?ts=1234) to some requests — req.url includes it raw, so
          // without stripping it first, path.join treats "?ts=1234" as
          // part of the filename and the lookup 404s even though the real
          // file exists on disk. This was the actual bug: only affected
          // pagefind-entry.json (the query-stringed request), not every
          // asset, so wasm/meta/fragment files still loaded — Pagefind's
          // language index just never became ready, so every search fell
          // through to zero results.
          const pathname = req.url.split('?')[0];
          const filePath = path.join(process.cwd(), 'dist', pathname);
          fs.readFile(filePath, (err, data) => {
            if (err) return next();
            if (filePath.endsWith('.js')) res.setHeader('Content-Type', 'text/javascript');
            if (filePath.endsWith('.json')) res.setHeader('Content-Type', 'application/json');
            res.end(data);
          });
        });
      },
    },
  };
}

// https://astro.build/config
export default defineConfig({
  site: 'https://drmontgomery.org',
  output: 'static',
  integrations: [serveDistPagefindDuringDev()],
  markdown: {
    // Every link inside article content (citations, sources) is an
    // absolute http(s) URL to an outside site — nav/card links elsewhere
    // on the site are plain Astro-templated hrefs, not Markdown, so this
    // only ever touches real external links.
    processor: unified({
      rehypePlugins: [
        [
          rehypeExternalLinks,
          {
            target: '_blank',
            rel: ['nofollow', 'noopener', 'noreferrer'],
          },
        ],
      ],
    }),
  },
});
