// @ts-check
import fs from 'node:fs';
import path from 'node:path';
import { defineConfig } from 'astro/config';
import { unified } from '@astrojs/markdown-remark';
import rehypeExternalLinks from 'rehype-external-links';

// `astro dev` serves live source via Vite — it never reads from dist/, so
// /pagefind/pagefind.js (only generated by the `pagefind` CLI step in
// `npm run build`, into dist/pagefind/) 404s under plain `npm run dev`,
// making /search look broken (silently falls back to only matching
// external Medical Conditions topic names). This serves whatever
// dist/pagefind/ exists from the last build directly during dev, so the
// normal dev workflow doesn't require switching to `astro preview` just to
// test search. Still requires at least one prior `npm run build` — there's
// no way around that; the index has to be generated from *something*.
function serveDistPagefindDuringDev() {
  return {
    name: 'serve-dist-pagefind-during-dev',
    hooks: {
      'astro:server:setup': ({ server }) => {
        server.middlewares.use((req, res, next) => {
          if (!req.url?.startsWith('/pagefind/')) return next();
          // Pagefind's loader appends a cache-busting query string
          // (e.g. ?ts=1234) to some requests — req.url includes it raw, so
          // without stripping it first, path.join treats "?ts=1234" as
          // part of the filename and the lookup 404s even though the real
          // file exists on disk. This was the actual bug: only affected
          // pagefind-entry.json (the query-stringed request), not every
          // asset, so wasm/meta/fragment files still loaded — Pagefind's
          // language index just never became ready, so every search fell
          // through to zero results.
          const pathname = req.url.split('?')[0];
          const filePath = path.join(process.cwd(), 'dist', pathname);
          fs.readFile(filePath, (err, data) => {
            if (err) return next();
            if (filePath.endsWith('.js')) res.setHeader('Content-Type', 'text/javascript');
            if (filePath.endsWith('.json')) res.setHeader('Content-Type', 'application/json');
            res.end(data);
          });
        });
      },
    },
  };
}

// TinaCMS's admin bundle is written directly to public/admin/index.html (by
// `tinacms build` or `tinacms dev`) — Astro's own build later copies it into
// dist/admin/index.html like any other static asset, and in production
// Cloudflare's static-asset serving resolves the clean URL /admin (and
// /admin/) straight to that file automatically. Vite's dev-server static
// serving does NOT do that same clean-URL resolution: /admin/index.html
// loads fine under `astro dev`, but /admin and /admin/ 404 (confirmed — this
// was reported as a real bug before realizing it was dev-only). Brett's
// documented workflow is visiting <site>/admin directly, so this normalizes
// the same behavior locally that Cloudflare already gives for free in prod.
function serveAdminIndexDuringDev() {
  return {
    name: 'serve-admin-index-during-dev',
    hooks: {
      'astro:server:setup': ({ server }) => {
        server.middlewares.use((req, res, next) => {
          if (req.url !== '/admin' && req.url !== '/admin/') return next();
          const filePath = path.join(process.cwd(), 'public', 'admin', 'index.html');
          fs.readFile(filePath, (err, data) => {
            if (err) return next();
            res.setHeader('Content-Type', 'text/html');
            res.end(data);
          });
        });
      },
    },
  };
}

// Same lucide "external-link" icon/paths used on the Medical Conditions and
// Search pages (see @lucide/astro's icons/external-link.ts) — reproduced as
// a raw hast tree here since rehype plugins can't render Astro components,
// and colored via the shared .external-link-icon class (global.css) so the
// color lives in one place. rehype-external-links wraps this content array
// in its own <span> at the end of the link automatically.
function externalLinkIconContent() {
  return [
    {
      type: 'element',
      tagName: 'svg',
      properties: {
        xmlns: 'http://www.w3.org/2000/svg',
        viewBox: '0 0 24 24',
        fill: 'none',
        stroke: 'currentColor',
        strokeWidth: 2,
        strokeLinecap: 'round',
        strokeLinejoin: 'round',
        className: ['external-link-icon'],
        ariaHidden: 'true',
      },
      children: [
        { type: 'element', tagName: 'path', properties: { d: 'M15 3h6v6' }, children: [] },
        { type: 'element', tagName: 'path', properties: { d: 'M10 14 21 3' }, children: [] },
        {
          type: 'element',
          tagName: 'path',
          properties: { d: 'M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6' },
          children: [],
        },
      ],
    },
    {
      type: 'element',
      tagName: 'span',
      properties: { className: ['sr-only'] },
      children: [{ type: 'text', value: ' (external site)' }],
    },
  ];
}

// https://astro.build/config
export default defineConfig({
  site: 'https://drmontgomery.org',
  output: 'static',
  integrations: [serveDistPagefindDuringDev(), serveAdminIndexDuringDev()],
  markdown: {
    // Every link inside article content (citations, sources) is an
    // absolute http(s) URL to an outside site — nav/card links elsewhere
    // on the site are plain Astro-templated hrefs, not Markdown, so this
    // only ever touches real external links. Same-tab (no target) plus an
    // icon + sr-only text, matching the site-wide external-link treatment.
    processor: unified({
      rehypePlugins: [
        [
          rehypeExternalLinks,
          {
            rel: ['nofollow'],
            content: externalLinkIconContent,
          },
        ],
      ],
    }),
  },
});
